apiVersion: v1
kind: Service
metadata:
  name: fortune-configmap-svc
spec:
  type: LoadBalancer
  ports:
  - name: http # http defined in pod file
    port: 80
    targetPort: 80
  selector:
    app: fortune-configmap
