apiVersion: v1
kind: Pod
metadata:
  name: ingester-configmap
  labels:
    app: ingester-configmap
spec:
  containers:
  - image: edswarchitect/k8s-ingester
    name: ingester
    volumeMounts:
    - name: ingester-data-configmap
      mountPath: /data
      readOnly: true
    ports:
    - containerPort: 9080
      protocol: TCP
  volumes:
  - name: ingester-data-configmap
    configMap:
      name: ingester-config
