apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toydisk2-pvc
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: "standard"
