apiVersion: v1
kind: PersistentVolume
metadata:
  name: toydisk-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: toydisk
    fsType: ext4
